gulp        = require 'gulp'
coffee      = require 'gulp-coffee'
concat      = require 'gulp-concat'
uglify      = require 'gulp-uglify'
imagemin    = require 'gulp-imagemin'
sourcemaps  = require 'gulp-sourcemaps'
